### ISSUE TITLE
Number of scientist deaths is always double of the reported value

### ISSUE THREAD

**Issue by geist22** [mefistotelis/swars#18]
Issue from the original game.

As in the title. For example, when the statistics screen after a mission reports "Scientists died - 3: Explosion in laboratory", and you check your reasearch tab, you've actually lost 6 instead of 3.

**Comment by mefistotelis** [comment]
Debug comment:
Related code is in forward_research_progress() function. Some of its sub-functions are not remade yet.

We also need an option which forces scientists lost on a mission, for easy testing of this feature. Maybe some generalized "force_rare_features" option.

**Comment by mefistotelis** [comment]
The issue should be fixed with [swars: Fixed double removal of accidentally died scientists](https://github.com/mefistotelis/swars/commit/77dc07877b0bf989b5b2ca0395a09263e127257d).

**Comment by geist22** [comment]
Did some testing and it does match the reported value now - at least when the deaths are actually announced. Also, the number of scientists can no longer go into the negative if too many die, never noticed that before. Good.

But I've noticed that sometimes the bars are drawn wrong now, like here:
![research](https://github.com/mefistotelis/swars/assets/107389189/3ca1e98a-3e0c-4d0c-8dac-675ac6e4094b)

Note that neither the number of scientists nor the funding changed during the research time. I do not know what triggers it, but it happens frequently.

**Comment by mefistotelis** [comment]
You mean that the extrapolated/planned research curve doesn't match the actual research progress?
That would mean that I count research differently than the original game. I wonder curious.

**Comment by geist22** [comment]
Yes. the progressed research (highlighted) looks correct, and it progresses that way normally. The estimated bar is wrong. It seems this sometimes happens when one research finishes and another starts.

I can reproduce it consistently like this:
1. Enable cheat mode (login with `POOSLICE` name)
2. Complete first mission with `Alt+C` cheat
3. Hold down `.` to get a bunch of money
4. Start body level 2 research and turn on auto-research
5. Press `U` to advance research

When legs level 2 finishes and research moves to legs level 3, it should show an unusually steep bar that doesn't match actual progress.

Another small thing: If your scientists are down to 0, research still costs money with passing of time, though obviously no research gets done. Not that anyone would play in such a situation, but might still be worth fixing just for the sake of it.

**Comment by mefistotelis** [comment]
> it does not look like their number scales linearly and additional scientists have diminishing returns).

Yes. Researches work in groups of 4, and each consecutive group adds up to 1/2 of what the last group produced.

Same for the funding - doubling the funding increases generated points by 1/2, tripling it adds 1/2 + 1/4, and so on.

The issue is due to integer overflow - the numbers are high enough that 32-bit integers can still overflow. Today it is easy to move to 64-bit computations for the intermediate results, so this issue didn't happen.

Not sure if I want to work on reproducing the original bug.. seem to make more sense to rebalance the game by just decreasing research requirements.
In KeeperFX, I did gave an option to re-enable some classical bugs - but they were required to keep old levels playable, and there were thousands of user-made levels.

You can check the algorithm used, here:
https://github.com/mefistotelis/swars/blob/a9e016c7fa5a2574886483638531e23f087d9780/src/research.c#L167

Zero science but costing - will fix that.

Buy Graviton Guns - Ha, I never tried that, outside of cheats. But you will still be able to do that - use the recurring missions to get more scientists and funds. Grab the scientists and the suitcases, then exit mission without completing - all the gains still register. Also, entering and exiting a mission always counts as at least 2 days (meaning two days progress of research), even if you exit immediately.

**Comment by geist22** [comment]
I never thought of entering and leaving the optional missions just to get free research time - clever! But keeping the rewards of abandoned missions feels very much like bugusing, like High Explosive dupe with restarting missions for example. My method felt within the rules of the game, as the research has always worked this way. To get enough money for 3 Gravition Guns, you really need to get as much money as you can, like rob every bank, pick up most dropped explosives before the blow up, and sell most guns between missions to re-acquire them again in the next mission.

But we're moving away from the topic. The doubled deaths are fixed, so I will close this issue and use a new one  (https://github.com/mefistotelis/swars/issues/47) for the research time.
